minimum_pre_commit_version: "2.9.2"
repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        exclude: ^docs/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 73b0f6d59bbfcb75e17a4653d581c9dfaca13969 # frozen: v0.12.5
    hooks:
      - id: ruff
        name: Ruff
        args: [--fix]

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: a4920527036bb9a3f3e6055d595849d67d0da066 # frozen: 25.1.0
    hooks:
      - id: black
        language_version: python3.13
        exclude: ^docs/

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # frozen: v2.4.1
    hooks:
      - id: codespell
        files: ^docs/.*\.md$
        additional_dependencies:
          - tomli
